### ISSUE TITLE
Version 0.2.1.0 on hackage, Version 0.2.0.0 in github

### ISSUE THREAD

**Issue by typetetris** [sdiehl/repline#18]
At the moment the master branch has a cabal file, which states version 0.2.0.0
but there is a version 0.2.1.0 on hackage.

I am confused? Where is the git repo for the code of version 0.2.1.0?

**Comment by sdiehl** [comment]
The version on master will be 0.2.2, it includes the new `exceptions` dependency. I haven't pushed this to Hackage yet.

**Comment by sdiehl** [comment]
This is fixed now.
