### ISSUE TITLE
Basic Repline example, commands not working

### ISSUE THREAD

**Issue by ssbothwell** [sdiehl/repline#19]
I was trying to get `Repline` working in a project of mine and wasn't able to get command options to work. So I made a test stack project where I copy pasted in the exact `Simple` example code and still the command options did not work:

```
Welcome!
>>> 
kirk   spock  mccoy
>>> kirk 
"kirk "
>>> spam
"spam"
>>> :say Hello Haskell
":say Hello Haskell"
>>> :help arg1 arg2 arg3
":help arg1 arg2 arg3"
```

I'm using the`lts-14.13` resolver. Here is a link to my sample project:
https://github.com/ssbothwell/replinetest

**Comment by ssbothwell** [comment]
Replacing the `Nothing` parameter to `evalRepl` with `Just ':'` fixes this issue. All the examples in the readme use `Nothing`.

**Comment by sdiehl** [comment]
This should be fixed now.
