### ISSUE TITLE
Support for haskeline 0.8

### ISSUE THREAD

**Issue by sjakobi** [sdiehl/repline#23]
Since `haskeline < 0.8` doesn't support GHC 8.10, that should also unblock compatibility with GHC 8.10.

**Comment by sdiehl** [comment]
This is fixed in 0.3.0. Note the API changes in the 0.3.0 changelog.
https://hackage.haskell.org/package/repline-0.3.0.0

Since the underlying `haskeline` breaks on GHC < 8.10 I'm currently not adding a shim for backwards compatibility.

**Comment by sjakobi** [comment]
Cheers! :)
