### ISSUE TITLE
Export MonadHaskeline

### ISSUE THREAD

**Issue by jmorag** [sdiehl/repline#36]
I have a small project I'd like to transition from using raw haskeline to this library. However, I make a lot of use of `getInputChar` directly to do things like ask the user a yes/no follow-up question after a command, and the lifted version defined in the `MonadHaskeline` class isn't exported. In fact, as far as I can tell, it isn't ever used in this library apart from defining other instances of MonadHaskeline. Is there a good reason not to use `getInputChar` directly with repline, or perhaps a more idiomatic solution to the problem of getting follow-up answers?

**Comment by sdiehl** [comment]
So really the design of this library is around "commands" as the unit of interaction with the repl. Effectively for writing shells for language interpreters as the primary use case. Some people use it for other things but the reason it doesn't export everything else is that it's really designed to be a simpler higher-level interface. The low-level Haskeline library always exists for anyone who needs to drop down to that level as an escape hatch. 

That's effectively what informed the design of the exports. I'm happy to revisit this assumption though if you have a specific patch you want to land for your project though.

**Comment by jmorag** [comment]
Having access to `getInputChar` is enough to get started with. There might be some way of extending `Multiline` with a `SingleChar` constructor in order to display a different banner and read a single character for the next command, but I haven't figured out a way to do that cleanly. Happy to close this now and open a PR later if I think of a nice way to integrate that functionality.

**Comment by sdiehl** [comment]
Yeah, if you want any change landed just submit a PR. I'm pretty happy to change the public API on this library so long as it doesn't regress.
