### ISSUE TITLE
Please provide a changelog

### ISSUE THREAD

**Issue by ocharles** [sdiehl/repline#4]

**Comment by sdiehl** [comment]
What in particular is the issue? I haven't added anything in like 2 years.

**Comment by ocharles** [comment]
I thought something had changed but it was something else. Either way,
every project should have a change log, so maybe consider this a reminder
for your next release :)

**Comment by sdiehl** [comment]
Please don't abuse the issue tracker for no reason like this.

**Comment by ocharles** [comment]
This is not abuse.
